CREATE TABLE vendedores (id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, nombre VARCHAR2(120) NOT NULL, email VARCHAR2(160) UNIQUE NOT NULL);
CREATE TABLE vehiculos (id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, marca VARCHAR2(80) NOT NULL, modelo VARCHAR2(80) NOT NULL, anio NUMBER(4) NOT NULL, precio NUMBER(12,2) NOT NULL CHECK(precio>0));
CREATE TABLE prospectos (id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, nombre VARCHAR2(120) NOT NULL, email VARCHAR2(160) NOT NULL, telefono VARCHAR2(40) NOT NULL, interes_vehiculo VARCHAR2(160) NOT NULL, etapa VARCHAR2(20) DEFAULT 'initial' NOT NULL CHECK(etapa IN ('initial','qualification','negotiation','closed')), vendedor_id NUMBER NOT NULL REFERENCES vendedores(id), resultado VARCHAR2(10) CHECK(resultado IN ('won','lost')), motivo_perdida VARCHAR2(400), ultima_actividad TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL);
CREATE TABLE ventas (id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, prospecto_id NUMBER UNIQUE NOT NULL REFERENCES prospectos(id), vehiculo_id NUMBER NOT NULL REFERENCES vehiculos(id), vendedor_id NUMBER NOT NULL REFERENCES vendedores(id), monto NUMBER(12,2) NOT NULL CHECK(monto>0), estado VARCHAR2(12) NOT NULL CHECK(estado IN ('completed','failed')), motivo_perdida VARCHAR2(400), creado_en TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL);
CREATE TABLE seguros (... , estado VARCHAR2(12) NOT NULL CHECK(estado IN ('prospected','sold')), creado_en TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL);
CREATE INDEX ix_prospectos_etapa ON prospectos(etapa);
CREATE INDEX ix_prospectos_actividad ON prospectos(ultima_actividad);
CREATE INDEX ix_ventas_estado ON ventas(estado);

